import {
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from "react-native";
import React, { useState } from "react";
import { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { RouteProp, useNavigation, useRoute } from "@react-navigation/native";
import { PlanTripStackParamsList } from "../navigation/PlanTripStack";
import { useUser } from "@clerk/expo";
import { Ionicons } from "@expo/vector-icons";
import { GoogleGenAI } from "@google/genai";

type ChatMessage = {
  from: "user" | "ai";
  text: string;
};

const suggestions = [
  "Best places to eat in",
  "3 Day itinerary to",
  "Top Attractions in",
];

const AIChatScreen = () => {
  const navigation =
    useNavigation<NativeStackNavigationProp<PlanTripStackParamsList>>();
  const route = useRoute<RouteProp<PlanTripStackParamsList, "AIChat">>();
  const location = route?.params.tripName;
  const { user: expoUser } = useUser();
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const ai = new GoogleGenAI({
    apiKey: process.env.EXPO_PUBLIC_GEMINI_API_KEY,
  });

  async function askAI(input: string) {
    const updatedMessages: ChatMessage[] = [
      ...messages,
      { from: "user", text: input },
    ];
    setMessages(updatedMessages);
    setInput("");
    setLoading(true);

    try {
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        config: {
          systemInstruction: `You are a helpful travel assistant for ${location}. 
              Give concise, practical advice about the destination.`,
        },
        contents: updatedMessages.map((msg) => ({
          role: msg.from === "user" ? "user" : "model",
          parts: [{ text: msg.text }],
        })),
      });
      const reply = response.text;
      if (!reply) {
        setMessages((prev) => [
          ...prev,
          { from: "ai", text: "Sorry, I could not fetch a response." },
        ]);
        return;
      }
      setMessages((prev) => [...prev, { from: "ai", text: reply! }]);
    } catch (error) {
      console.error("AI Assistant error", error);
      setMessages((prev) => [
        ...prev,
        { from: "ai", text: "Sorry, there was an error fetching a response." },
      ]);
    } finally {
      setLoading(false);
    }
  }

  async function sendEmail(mesage: string) {}

  return (
    <View className="flex-1 bg-white pt-14 px-4">
      <View className="flex-row items-center mb-4">
        <Pressable>
          <Ionicons name="arrow-back" color={"#000"} size={24} />
        </Pressable>
        <Text className="ml-4 text-lg font-semibold">AI Assistant</Text>
      </View>

      <View className="bg-orange-100 p-3 rounded-md mb-2">
        <Text className="text-sm text-orange-600 font-medium">
          4 messages left <Text className="underline">Get More</Text>
        </Text>
      </View>

      <View className="bg-blue-50 p-3 rounded-md mb-4 mt-2">
        <Text className="text-sm text-orange-600 font-medium">
          AI Assistant does not make edits to your trip plan.
        </Text>
        <Text className="text-sm text-blue-600 mt-1">
          Information generated by AI Assistant may not be accurate.
        </Text>
      </View>

      <View className="mb-4">
        <View className="font-semibold">
          Don't know what to ask? Try these examples:
        </View>
        <View className="flex-row flex-wrap gap-2">
          {suggestions.map((suggestion) => (
            <Pressable
              onPress={() => askAI(`${suggestion} ${location}`)}
              key={suggestion}
              className="bg-gray-100 px-4 py-2 rounded-full mb-2 mt-1"
            >
              <Text className="text-sm text-gray-800">
                {suggestion} {location}
              </Text>
            </Pressable>
          ))}
        </View>
      </View>

      <ScrollView>
        {messages.map((msg) => (
          <View key={msg.text} className="mb-3">
            <View
              className={`p-3 rounded-lg ${msg.from === "user" ? "bg-gray-100 self-end" : "bg-orange-50 self-start"}`}
            >
              <Text className="text-sm">{msg.text}</Text>
            </View>
            {msg.from === "ai" && (
              <Pressable
                onPress={() => sendEmail(msg.text)}
                className="self-start mt-1"
              >
                <Ionicons name="mail" size={20} color={"#007AFF"} />
              </Pressable>
            )}
          </View>
        ))}
        {loading && (
          <View className="bg-orange-50 self-start p-3 rounded-lg mb-3">
            <ActivityIndicator size={"small"} color={"orange"} />
          </View>
        )}
      </ScrollView>

      <KeyboardAvoidingView
        keyboardVerticalOffset={80}
        behavior={Platform.OS === "ios" ? "padding" : "height"}
      >
        <View className="flex-row items-center border rounded-full px-4 py-2 mb-4 bg-gray-50">
          <TextInput
            className="flex-1 text-sm"
            placeholder="Ask any travel related questions"
            value={input}
            onChangeText={setInput}
          />
          <Pressable onPress={() => askAI(input)} disabled={!input.trim()}>
            <Ionicons name="arrow-forward" size={24} color={"black"} />
          </Pressable>
        </View>
      </KeyboardAvoidingView>
    </View>
  );
};

export default AIChatScreen;

const styles = StyleSheet.create({});
